[features]
seeds = false
skip-lint = false

[workspace]
# Prevent Anchor from treating build artifacts as programs.
# NOTE: scripts should `mkdir -p programs/target` before invoking Anchor in clean environments.
exclude = ["programs/target"]

[programs.localnet]
stark_verifier = "StArKSLbAn43UCcujFMc5gKc8rY2BVfSbguMfyLTMtw"
murkl_program = "muRkDGaY4yCc6rEYWhmJAnQ1abdCbUJNCr4L1Cmd1UF"

[programs.devnet]
stark_verifier = "StArKSLbAn43UCcujFMc5gKc8rY2BVfSbguMfyLTMtw"
murkl_program = "muRkDGaY4yCc6rEYWhmJAnQ1abdCbUJNCr4L1Cmd1UF"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
